# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b91611fac4b821910133c9596c4832ff9cff193a1d257f4b94e14ec5512ffd7d2f2ebaefbc661b19cce058d1010f99488f9acf3664df45042fb891033222b9f

test:
  secret_key_base: 7aa3f5de1615f065a36ed1616addffdbc7cb6daf00983d2faa5644be95537c1519cabc3101090f24e9d0f8cd6f6083bbe053cb553cc3fddf7004bf8908292b84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
